# application.yml

server:
  port: 3334 # 应用启动端口

spring:
  application:
    name: movie-vault # 应用名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 8.x 驱动类名
    url: jdbc:mysql://192.168.0.100:3306/movie_vault?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai # 数据库连接URL
    username: movieuser # 数据库用户名
    password: Aa82250228 # 数据库密码
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # Jackson 日期格式
    time-zone: GMT+8 # Jackson 时区

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启 SQL 日志打印到控制台（开发用）
  global-config:
    db-config:
      id-type: auto  # 主键自增策略
  mapper-locations: classpath*:mapper/**/*.xml  # MyBatis-Plus XML 映射文件位置

# 日志配置
logging:
  level:
    com.ason.movievault.mapper: debug # 设置 mapper 包的日志级别为 debug，用于输出 SQL
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 控制台日志输出格式